//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Quản_lý_sách_trong_thư_viện.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUAN_TRI
    {
        public int MaQuanTri { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public string QuyenHan { get; set; }
    }
}
